# Generated by Django 4.2.27 on 2025-12-20 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_categoryicon_financialgoal_tag_scheduledtransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фильтра')),
                ('parameters', models.JSONField(verbose_name='Параметры фильтра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LEND', 'Я дал в долг'), ('BORROW', 'Я взял в долг')], max_length=6, verbose_name='Тип долга')),
                ('person', models.CharField(max_length=100, verbose_name='Кому / У кого')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Погашен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
